########################################
# Package: Windows Appx Packages Modification Script
# Type: CMD (Command Line) / PowerShell
# Platform: Windows 10 / Windows 11
# Source Code: https://github.com/michalselma/WinCTS
########################################

# List updated for: Windows 10 Pro 21H2 10.0.19041 sp1288
# Reviewed on 2022-09-20

# 0-Uninstall/Remove, 1-Install, 2-Don't change/skip

Microsoft.Microsoft3DViewer=0
Microsoft.WindowsAlarms=0
Microsoft.DesktopAppInstaller=0
Microsoft.WindowsCalculator=2
Microsoft.WindowsCamera=2
Microsoft.549981C3F5F10=0
Microsoft.WindowsFeedbackHub=0
Microsoft.GetHelp=0
Microsoft.ZuneMusic=0
Microsoft.HEIFImageExtension=2
microsoft.windowscommunicationsapps=0
Microsoft.WindowsMaps=0
Microsoft.MicrosoftSolitaireCollection=0
Microsoft.WindowsStore=2
Microsoft.MixedReality.Portal=0
Microsoft.ZuneVideo=0
Microsoft.MicrosoftOfficeHub=0
Microsoft.Office.OneNote=0
Microsoft.MSPaint=0
Microsoft.People=0
Microsoft.Windows.Photos=0
Microsoft.SkypeApp=0
Microsoft.ScreenSketch=0
Microsoft.MicrosoftStickyNotes=0
Microsoft.Getstarted=0
Microsoft.WindowsSoundRecorder=0
Microsoft.BingWeather=0
Microsoft.WebMediaExtensions=2
Microsoft.WebpImageExtension=2
Microsoft.XboxApp=0
Microsoft.XboxGamingOverlay=0
Microsoft.Xbox.TCUI=0
Microsoft.YourPhone=0
1527c705-839a-4832-9118-54d4Bd6a0c89=2
c5e2524a-ea46-4f67-841f-6a9465d9d515=2
E2A4F912-2574-4A75-9BB0-0D023378592B=2
F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE=2
Microsoft.AAD.BrokerPlugin=2
Microsoft.AccountsControl=2
Microsoft.AsyncTextService=2
Microsoft.BioEnrollment=2
Microsoft.CredDialogHost=2
Microsoft.ECApp=2
Microsoft.LockApp=2
Microsoft.MicrosoftEdge=2
Microsoft.MicrosoftEdge.Stable=2
Microsoft.MicrosoftEdgeDevToolsClient=2
Microsoft.StorePurchaseApp=2
Microsoft.VP9VideoExtensions=2
Microsoft.Wallet=0
Microsoft.Win32WebViewHost=2
Microsoft.Windows.Apprep.ChxApp=2
Microsoft.Windows.AssignedAccessLockApp=2
Microsoft.Windows.CallingShellApp=2
Microsoft.Windows.CapturePicker=2
Microsoft.Windows.CloudExperienceHost=2
Microsoft.Windows.ContentDeliveryManager=2
Microsoft.Windows.NarratorQuickStart=2
Microsoft.Windows.OOBENetworkCaptivePortal=2
Microsoft.Windows.OOBENetworkConnectionFlow=2
Microsoft.Windows.ParentalControls=2
Microsoft.Windows.PeopleExperienceHost=2
Microsoft.Windows.PinningConfirmationDialog=2
Microsoft.Windows.Search=2
Microsoft.Windows.SecHealthUI=2
Microsoft.Windows.SecureAssessmentBrowser=2
Microsoft.Windows.ShellExperienceHost=2
Microsoft.Windows.StartMenuExperienceHost=2
Microsoft.Windows.XGpuEjectDialog=2
Microsoft.XboxGameCallableUI=2
Microsoft.XboxGameOverlay=0
Microsoft.XboxIdentityProvider=2
Microsoft.XboxSpeechToTextOverlay=0
MicrosoftWindows.Client.CBS=2
MicrosoftWindows.UndockedDevKit=2
NcsiUwpApp=2
Windows.CBSPreview=2
windows.immersivecontrolpanel=2
Windows.PrintDialog=2
Microsoft.Advertising.Xaml=0
Microsoft.NET.Native.Framework.1.7=2
Microsoft.NET.Native.Framework.2.2=2
Microsoft.NET.Native.Runtime.1.7=2
Microsoft.NET.Native.Runtime.2.2=2
Microsoft.Services.Store.Engagement=2
Microsoft.UI.Xaml.2.0=2
Microsoft.VCLibs.140.00=2
Microsoft.VCLibs.140.00.UWPDesktop=2
