########################################
# Package: Windows Power Options Script
# Type: CMD (Command Line) / PowerShell
# Platform: Windows 10 / Windows 11
# Source Code: https://github.com/michalselma/WinCTS
########################################

# **** Power plan standard settings ****
# Turn off the display - On Battery (Time in minutes or 0=Never)
change.monitor-timeout-dc=10
# Turn off the display - Plugged in (Time in minutes or 0=Never)
change.monitor-timeout-ac=20
# Put the computer to sleep - On Battery (Time in minutes or 0=Never)
change.standby-timeout-dc=0
# Put the computer to sleep - Plugged in (Time in minutes or 0=Never)
change.standby-timeout-ac=0

# **** Power plan advanced settings ****
# Hibernate computer - On Battery (Time in minutes or 0=Never)
change.hibernate-timeout-dc=0
# Hibernate computer - Plugged in (Time in minutes or 0=Never)
change.hibernate-timeout-ac=0
# Turn off hard drive - On Battery (Time in minutes or 0=Never)
change.disk-timeout-dc=0
# Turn off hard drive - Plugged in (Time in minutes or 0=Never)
change.disk-timeout-ac=0

# **** Power button and lid settings ****
# Lid open wake action - On Battery (0=Do Nothing, 1=Turn on the display)
setidx_dc.LIDOPENWAKE=1
# Lid open wake action - Plugged in (0=Do Nothing, 1=Turn on the display)
setidx_ac.LIDOPENWAKE=1
# Lid switch close action - On Battery (0=Do Nothing, 1=Sleep, 2=Hibernate, 3=ShutDown)
setidx_dc.LIDACTION=0
# Lid switch close action - Plugged in (0=Do Nothing, 1=Sleep, 2=Hibernate, 3=ShutDown)
setidx_ac.LIDACTION=0
# Power button action - On Battery (0=Do Nothing, 1=Sleep, 2=Hibernate, 3=ShutDown)
setidx_dc.PBUTTONACTION=3
# Power button action - Plugged in (0=Do Nothing, 1=Sleep, 2=Hibernate, 3=ShutDown)
setidx_ac.PBUTTONACTION=3
# Power button forced shutdown - On Battery (0=Off, 1=On)
setidx_dc.SHUTDOWN=1
# Power button forced shutdown - Plugged in (0=Off, 1=On)
setidx_ac.SHUTDOWN=1
# Sleep button action - On Battery (0=Do Nothing, 1=Sleep, 2=Hibernate, 3=ShutDown)
setidx_dc.SBUTTONACTION=1
# Sleep button action - Plugged in (0=Do Nothing, 1=Sleep, 2=Hibernate, 3=ShutDown)
setidx_ac.SBUTTONACTION=1
