########################################
# Package: Windows Tweaks Script
# Type: CMD (Command Line) / PowerShell
# Platform: Windows 10 / Windows 11
# Source Code: https://github.com/michalselma/WinCTS
########################################

# List updated for: Windows 10 Pro 21H2 10.0.19041 sp1288
# Reviewed on 2022-10-05

# 0-Disable, 1-Enable, 2-Don't change/skip

#### Settings -> Privacy -> App permisions (UWP) ####
Location = 0
Camera = 2
Microphone = 2
VoiceActivation = 2
Notifications = 2
AccountInfo = 2
Contacts = 2
Calendar = 2
PhoneCalls = 2
CallHistory = 2
Email = 2
Tasks = 2
Messaging = 2
Radios = 2
OtherDevices = 2
BackgroundApps = 2
AppDiagnostics = 2
Documents = 2
Pictures = 2
Videos = 2
FileSystem = 2

#### Settings -> Update&Security -> Windows Update ####
UpdateForOtherMsProd = 1