########################################
# Package: Windows Tweaks Script
# Type: CMD (Command Line) / PowerShell
# Platform: Windows 10 / Windows 11
# Source Code: https://github.com/michalselma/WinCTS
########################################

# List updated for: Windows 10 Pro 21H2 10.0.19041 sp1288
# Reviewed on 2022-10-05

# 0-Disable, 1-Enable, 2-Don't change/skip

#### Control Panel -> Appearance and Personalization -> File Explorer Options ####
ShowHiddenFilesAndFolders = 1
HideKnownFileExtensions = 0
HideProtectedSystemFiles = 0

#### Settings -> Personalization -> Start ####
#[Not Implemented] ShowRecentlyAddedApps = 0
#[Not Implemented] ShowMostUsedApps = 0
ShowRecentlyOpenedItems = 0

#### Settings -> Personalization -> Taskbar (or in some cases Taskbar -> 'Right Click') ####
TaskbarSmallIcons=0
ShowAllTrayIcons=1
PeopleIcon=0
ShowTaskViewButton=1
TaskbarSearchIcon = 0
TaskbarSearchBox = 0

#### Settings -> Privacy -> Windows permisions ####
AdvertisingID = 0
WebAccessToLangList = 0
LetTrackAppLaunches = 0
TailoredExperiences = 0

#### Settings -> Privacy -> App permisions (UWP) ####
Location = 0
Camera = 2
Microphone = 2
VoiceActivation = 0
Notifications = 0
AccountInfo = 0
Contacts = 0
Calendar = 0
PhoneCalls = 0
CallHistory = 0
Email = 0
Tasks = 0
Messaging = 0
Radios = 0
OtherDevices = 0
BackgroundApps = 0
AppDiagnostics = 0
Documents = 0
Pictures = 0
Videos = 0
FileSystem = 0

#### Settings -> System -> About -> Advanced system settings ####
RemoteAssistance = 0

#### Settings -> Update&Security -> Windows Update ####
UpdateForOtherMsProd = 1
