########################################
# Package: Windows Tweaks Script
# Type: CMD (Command Line) / PowerShell
# Platform: Windows 10
# Source Code: https://github.com/michalselma/WinCTS
########################################

# List updated for: Windows 10 Pro 21H2 10.0.19041 sp1288
# Reviewed on 2022-11-06

# 0-Disable, 1-Enable, 2-Don't change/skip

#### Applicaions ####
Cortana = 0
MapUpdates = 0
#[Not Implemented] OneDrive = 0

#### Corporate / Group and Local Policy ####
WUPolicyControl = 0

#### Hardware and Hardware Privacy ####
WiFiSense = 0

#### Privacy ####
AppSuggestions = 0
SilentInstalledApps = 0
ActivityHistory = 0
Telemetry = 0

#### Services ####
WinSearchIndexing = 0
WAPPush = 0
DiagTrack = 0

#### ScheduledTasks ####
Feedback = 0
ErrorReporting = 0

#### System ####
UWPSwapFile = 2

#### User Interface ####
BuildNumberOnDesktop = 1
WebSearchResultForTaskbarSearch = 0
UnpinStartMenuTiles = 1
UnpinTaskbarIcons = 1