########################################
# Package: Windows Tweaks Script
# Type: CMD (Command Line) / PowerShell
# Platform: Windows 10 / Windows 11
# Source Code: https://github.com/michalselma/WinCTS
########################################

# List updated for: Windows 10 Pro 21H2 10.0.19041 sp1288
# Reviewed on 2022-10-01

# 0-Disable, 1-Enable, 2-Don't change/skip

### Privacy ###
Telemetry = 0
SmartScreen = 2
WebSearch = 0
AppSuggestions = 0
ActivityHistory = 0
Feedback = 0
TailoredExperiences = 0
AdvertisingID = 0
WebLangList = 0
ErrorReporting = 0
DiagTrack = 0
WAPPush = 0
ClearRecentDocsOnExit = 1
NoRecentDocsHistory = 1
RemoteAssistance = 0

### Hardware and Hardware Privacy ###
WiFiSense = 0
LocationAndLocationScripting = 0
LocationSensors = 0
Biometrics = 0
Camera = 2
Microphone = 2

### User Interface - Desktop ###
BuildNumberOnDesktop = 1

### Applicaions ###
Cortana = 0
MapUpdates = 0
OneDrive = 0

### Services ###
SharedExperiences = 0
WinSearchIndexing = 0

### Corporate / Local Policy ###
WUPolicyControl = 0